object Versions {
  val boilerplate: String  = "0.6.1"
  val coursier: String     = "1.0.0"
  val mdoc: String         = "1.3.6"
  val sbtDoctest: String   = "0.9.5"
  val sbtGhPages: String   = "0.6.3"
  val sbtHeader: String    = "5.2.0"
  val sbtPgp: String       = "2.0.0"
  val sbtRelease: String   = "1.0.12"
  val sbtScalafmt: String  = "2.0.7"
  val sbtSite: String      = "1.4.0"
  val sbtSonatype: String  = "3.8"
  val sbtUnidoc: String    = "0.4.2"
  val scalajs: String      = "0.6.29"
  val scalajsCross: String = "0.6.1"
  val scalastyle: String   = "1.0.0"
  val scoverage: String    = "1.6.0"
  val wartRemover: String  = "2.4.2"
}
