object Versions {
  val boilerplate: String  = "0.7.0"
  val mdoc: String         = "2.6.3"
  val sbtDoctest: String   = "0.11.1"
  val sbtGhPages: String   = "0.8.0"
  val sbtHeader: String    = "5.10.0"
  val sbtPgp: String       = "2.3.1"
  val sbtRelease: String   = "1.4.0"
  val sbtScalafix: String  = "0.13.0"
  val sbtScalafmt: String  = "2.5.2"
  val sbtSite: String      = "1.7.0"
  val sbtSonatype: String  = "3.12.2"
  val sbtUnidoc: String    = "0.5.0"
  val scalajs: String      = "1.18.1"
  val scalajsCross: String = "1.3.2"
  val scoverage: String    = "2.2.2"
  val wartRemover: String  = "3.2.5"
}
